// Generated by CoffeeScript 1.4.0

/*
Sticky Elements Shortcut for jQuery Waypoints - v2.0.1
Copyright (c) 2011-2013 Caleb Troughton
Dual licensed under the MIT license and GPL license.
https://github.com/imakewebthings/jquery-waypoints/blob/master/licenses.txt
*/


(function() {
  var $, defaults, wrap;

  $ = window.jQuery;

  defaults = {
    wrapper: '<div class="sticky-wrapper" />',
    stuckClass: 'stuck'
  };

  wrap = function($elements, options) {
    $elements.wrap(options.wrapper);
    $elements.each(function() {
      var $this;
      $this = $(this);
      $this.parent().height($this.height());
      return true;
    });
    return $elements.parent();
  };

  $.waypoints('extendFn', 'sticky', function(options) {
    var $wrap;
    options = $.extend({}, $.fn.waypoint.defaults, defaults, options);
    $wrap = wrap(this, options);
    options.handler = function(direction) {
      var $sticky, shouldBeStuck;
      $sticky = $(this).children(':first');
      shouldBeStuck = direction === 'down' || direction === 'right';
      return $sticky.toggleClass(options.stuckClass, shouldBeStuck);
    };
    $wrap.waypoint(options);
    return this;
  });

}).call(this);
